// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT5yv9V6z8LDBaGP5fgM8wFS6Gm7PtU64',
    appId: '1:21782418853:web:3824eedf2ddef81cce044c',
    messagingSenderId: '21782418853',
    projectId: 'chat-app-e1480',
    authDomain: 'chat-app-e1480.firebaseapp.com',
    storageBucket: 'chat-app-e1480.appspot.com',
    measurementId: 'G-VE1P0XGJDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyXSNW2fRVUIlr8oGoPomEB2naBsgVAOw',
    appId: '1:21782418853:android:01cb7fedf1dafcacce044c',
    messagingSenderId: '21782418853',
    projectId: 'chat-app-e1480',
    storageBucket: 'chat-app-e1480.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Cqhg6dFuKiSlrcMw4OWmRVdeyC2pdJ0',
    appId: '1:21782418853:ios:192e8b70fc46d621ce044c',
    messagingSenderId: '21782418853',
    projectId: 'chat-app-e1480',
    storageBucket: 'chat-app-e1480.appspot.com',
    iosClientId: '21782418853-4mpoedlfhha4p2mfuig5nut64bqg2g7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Cqhg6dFuKiSlrcMw4OWmRVdeyC2pdJ0',
    appId: '1:21782418853:ios:192e8b70fc46d621ce044c',
    messagingSenderId: '21782418853',
    projectId: 'chat-app-e1480',
    storageBucket: 'chat-app-e1480.appspot.com',
    iosClientId: '21782418853-4mpoedlfhha4p2mfuig5nut64bqg2g7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
